#![cfg(all(feature = "cuda", not(slhav2_cuda_ptx)))]

//! Explicit failure surface for hardware validation requested without real PTX.

#[test]
#[ignore = "requires PTX generated by nvcc or supplied through SLHAV2_PTX_PATH"]
fn test_cuda_ptx_unavailable() {
    panic!(
        "CUDA validation was requested, but no real PTX is available. \
         Install nvcc, set SLHAV2_NVCC, or provide SLHAV2_PTX_PATH."
    );
}
